### ISSUE TITLE
Add password strength estimation

### ISSUE THREAD

**Issue by sgade** [sgade/hgots-node#25]
People should use strong passwords.
Use [zxcvbn](https://github.com/dropbox/zxcvbn) by @Dropbox to help users create a strong password.

Maybe form-submit could be disabled if a weak password was chosen.

**Comment by jhbruhn** [comment]
Or we display some kind of bargraph thingie, should'nt be too difficult to make.

**Comment by sgade** [comment]
That was what I thought about.

We could have some kind of "progressbar", color-coded, and only allow if it at least mediocre.

**Comment by sgade** [comment]
Added in 4fbf064ab243c492ff4fb01d47229a7f4ae5ad17, extended in 872173a1397ec75fa78617fb68e171e5075c7ea2 and fixed in a271f3c0c1a6917b628d89d63cc4e37c049ea3a4.

Finally done. Thanks to [StackOverflow](http://stackoverflow.com/a/23250935/2517996).
