### ISSUE TITLE
Add pagination to user list

### ISSUE THREAD

**Issue by sgade** [sgade/hgots-node#27]
Showing all users at once is just really blowing not-so-performant computers.

Maybe add pagination, could also be implemented as **infinite scrolling**?

**Comment by jhbruhn** [comment]
Infinite scrolling tends to explode, we should stick to traditional pagination.

**Comment by sgade** [comment]
Ok, sounds reasonable.

**Comment by sgade** [comment]
Is this even worth it because the right side panel slides with the scroll location.
What do you think, @jhbruhn?
